### ISSUE TITLE
[QUESTION] remove customize area?

### ISSUE THREAD

**Issue by rigler86** [benbusby/whoogle-search#100]
Is it possible to remove the customize area? I wanna make this as easy as possible for my family to use. Will be used on our home server accessible by about 40 people in our family. I wanna keep them from messing with the settings. 

Would love to have the customize option via the private network web ui and not on the public facing part.

**Comment by rigler86** [comment]
After reading another issue post by another user I see where you state how to hide the customize area. Would still love to see it like for private facing.

**Comment by benbusby** [comment]
As of the latest release, you shouldn't need to hide the customization area since settings are handled on a per-session basis (provided session cookies are enabled). If cookies aren't enabled then user's share a generic "default" profile where modifications are applied permanently as before. 

Otherwise I'm going to close this and merge it in as a condition to be met for #60 since it should be included in that effort.
