### ISSUE TITLE
Auto focus to search bar

### ISSUE THREAD

**Issue by KizunaH** [benbusby/whoogle-search#101]
Currently when we load whoogle on web browser then necessary to click on search bar for start to type but [dad](https://google.com) doesn't have such problem ;)

**Comment by benbusby** [comment]
This should (finally) be fixed with dfb1e81fa12e2cc9ccc75a193fd4afdcb79d01e9. The fix is available now on the `develop` branch, and should be available soon on the docker `beta` tag. I'm planning to make a new release to the main branch this week, so you should see it there as well once that's done.
