### ISSUE TITLE
[BUG] Replit.com Code Does not work Anymore

### ISSUE THREAD

**Issue by 2zzly** [benbusby/whoogle-search#1030]
Hangs forever then stops after this is displayed in the console:

Requirement already satisfied: toml in ./venv/lib/python3.8/site-packages (from pytest==6.2.5->-r requirements.txt (line 26)) (0.10.2)
WARNING: pip is using a content-addressable pool to install files from. This experimental feature is enabled through --use-feature=content-addressable-pool and it is not ready for production.

**Deployment Method**
- [X] Replit.com (one-click deploy)

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [0.8.2] Version [version number]

**Comment by E-Baler** [comment]
Hello, same issue - Thanks !!

**Comment by benbusby** [comment]
I'm not able to reproduce this issue. I just went through the whole deploy process for Repl.it and it worked fine. The error message also doesn't indicate any issues, it's just a warning from pip when installing a package.

I also am probably not going to continue supporting Repl.it if something does break again, because issues with their deployment process come up a lot, and I don't want to have to maintain a deployment target that's constantly changing.
