### ISSUE TITLE
[QUESTION] can't get whoogle start with systemd

### ISSUE THREAD

**Issue by LeOS-GSI** [benbusby/whoogle-search#1060]
I have problems getting whoogle started via whoogel.service on my Linux Mint. attached my file. When I'm trying to start it I get this error message: 
`Failed to start whoogle.service: Unit whoogle.service has a bad unit file setting`

what am I doing wrong ?

as soon as terminal is closed I can't start it anymore. when I try run from main whoogle folder, I'm getting command not found. 
[whoogle.service.txt](https://github.com/benbusby/whoogle-search/files/12475187/whoogle.service.txt)

EDIT: I have renamed it to .txt, otherwise I can't attach

**Comment by benbusby** [comment]
Can you paste the contents of your whoogle systemd service file here? The "has a bad unit file setting" error can be due to having spaces surrounding the `=` in your file.

For example:

`ExecStart = /path/to/whoogle`

would need to be changed to

`ExecStart=/path/to/whoogle`

Closing for now since this seems like it might just be a syntax issue, but feel free to keep commenting here and I'll continue helping out wherever I can.
