### ISSUE TITLE
[FEATURE] Fallback to custom search provider

### ISSUE THREAD

**Issue by moritzfl** [benbusby/whoogle-search#1099]
**Fallback to custom search provider if whoogle breaks**
When whoogle fails to pull the results from google, it would be good to have the option to be forwarded to an alternative search engine with the search query that whoogle received.

https://whoogle.example.com/search?q=fail -> "It seems like whoogle is broken at the moment, would you like to continue on ecosia?" -> click "Yes" -> https://www.ecosia.org/search?q=fail

**Additional context**
I have whoogle set up as the default search engine for all devices in our household and at work.
While this only happened to me once so far, whoogle can and will eventually break when google introduces incompatible changes. In this case, the user has to switch open another search engine and reenter the search text. Or even worse - reconfigure the default search engine and perhaps not switch it back afterwards ;)

**Comment by GGLVXD** [comment]
So can i make it auto redirect to google when ever its ratelimited kr someting

**Comment by benbusby** [comment]
I just pushed a change that addresses this in a slightly different way. Rather than having users configure a specific fallbacks, the error page has been updated to display a list of other search providers (including Google), and also will appear after any exception occurs in the app (rather than only appearing when ratelimited). I think this is a simpler approach since it doesn't require anyone to define a new environment variable, and also allows users to try out multiple other options if they don't like the results they get from another source.
