### ISSUE TITLE
Remove alternate frontend which geoblock

### ISSUE THREAD

**Issue by ckr9** [benbusby/whoogle-search#1108]
**Describe the bug**
Please remove alternate frontends which geoblock. It really hampers user experience. Further whoogle keeps choosing these instances for me. example : reddit.utsav2.dev

Please remove these type of instances.

Thanks

**To Reproduce**

use alternate frontends.

**Deployment Method**

All

**Version of Whoogle Search**
All

**Comment by benbusby** [comment]
This is a https://github.com/benbusby/farside issue, Whoogle doesn't control which redirects are used. I'd recommend opening an issue there instead, or you can set the redirects to specific instances rather than Farside redirects via the [environment variables](https://github.com/benbusby/whoogle-search?tab=readme-ov-file#environment-variables).
