### ISSUE TITLE
[BUG] WHOOGLE_ALT_YT set to selfhosted invidous with domain name include “m.” will change to “//”

### ISSUE THREAD

**Issue by 6F3ryYosFLJU** [benbusby/whoogle-search#1125]
**Describe the bug**

I have a domain name e.g. abcm.com
My invidious instance is invidious.abcm.com
Set WHOOGLE_ALT_YT to invidous.abcm.com
Although the text of the result is normal e.g. invidious.abcm.com/@ExplainingComputers
All the underlying returned link become invidious.abc//com/@ExplainingComputers

seems like “SKIP_PREFIX” in app/utils/result.py cause the problem

**To Reproduce**
1) have a domain with “m.”
2) Set WHOOGLE_ALT_YT to the domain name
3) Check the underlying link, all “m.” change to //

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] IOS
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] 1.62

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benbusby** [comment]
@6F3ryYosFLJU Which version of Whoogle are you using? The `m.` replacement only happens if the link contains `//m.` (i.e. `https://m.youtube.com`), and setting `WHOOGLE_ALT_YT` to the link you mentioned works fine for me.

Closing for now because I think this will be fixed by updating to the latest Whoogle release (and potentially rebuilding the docker image from scratch), but reopen if you're on the latest version and still need help.
