### ISSUE TITLE
[BUG] <search results are unacceptable and far away from reality>

### ISSUE THREAD

**Issue by joan-carles** [benbusby/whoogle-search#123]
The performance and the searching results are useless. The experience in my case is not positive.

I'm spanish. I do a correct setup but Whoogle is not able to find many websites. For instance I do a search by

1. Geekland.eu
2. Ugeek
3. etc..

This domains exists. But Whoogle is not able to find anything. Seems that for whoogle the mentioned websites doesn't exist. So probably the filter results you do offer a bad experience to me... I'm not able to find website that I usually visit using Whoogle.

**Comment by joan-carles** [comment]
I rectify.

If you leave the default configuration according to server location the search results are fine. The problem is when you specify a country.

However the behaviour is not correct. If My server is in Spain then Default configuration option and Spain option should give you the same results. And the problem is they give you such a different results.

Rgds

**Comment by benbusby** [comment]
The filtering portion of Whoogle doesn't remove any results returned from a query, it just filters out ads / sponsored content from the view. 

Unfortunately, the issue you're describing is Google-specific behavior that I can't really modify on my end. When the Whoogle user config is updated, all that happens is the query that is forwarded to Google includes a country code in the param field. The results that they return with that updated param are entirely up to them, since Whoogle is a *metasearch* engine and not an independent search engine (in other words, I don't pick or choose which results to include or exclude). The fact that you're seeing different results depending on country tells me that Google is specifically only returning results that originate from that particular country, which is why Geekland.eu, for example, might not be showing up (since it isn't a Spanish website). Can't say with 100% certainty though.

**Comment by joan-carles** [comment]
Hi. I strongly believe something is not working correctly. 

geekland.eu is Spanish blog. The server is located in US nut most of the visits come from Spain. Now I'm using whoogle in a VPS in Switzerland and I'm in Spain. With this configuration more or less works:

https://imgur.com/SUE09Nz.png

However this isn't the logical config because the server is located in Switzerland... So to obtain the same search results as google.es you should use this config:

https://imgur.com/eKnalZP.png

But when I use the last config geekland.eu and many domains are missing from the searching results. Even if you search the word geekland the first search result is an IT store from USA. This is not normal from my logical point of view doesn't work as expected. I don't know if its Google's problem or not. What I ensure you is that user experience using what should be the logical configuration is bad.

I also have whoogle installed in a Raspberry Pi at home. With the Pi I use the first config mentioned and when you search google translator the searching results give you the extension finished with .es and all the searching results are perfect. But when I change it to the second gives me the .com extension and many searching results are missing.

So my conclusion is When you change the country parameter something fails. Many searching results disappear. Something must fail as it's not logical at all to obtain better search results with "default server location" rather than chosing your own country.

If worked fine whoogle is very useful. If you love in countries that google is Blocked (China) you can easily use google installing whoogle in a VPS.

**Comment by benbusby** [comment]
Right, I understand. So I think what Google does with the "country" parameter is they check the actual location of the server, nothing more. I validated that the `country` param does indeed remove results, but all of the results on the page in my test seem to be running on servers that originate from that country. 

Ultimately I think the only real solution for now is to clarify the wording on the config page to specify what the country parameter actually does to the search query (i.e. update it to say "Show results only from this country", since apparently that's how Google treats it). I can't do anything to change the behavior of how Google performs the search beyond that though.

**Comment by joan-carles** [comment]
Hi thanks to reply. I will keep on using it and report you if have relevant comments. What I'm sure is the whoogle I have at home doesn't give the same searching results as the one in switzerland. Maybe could help add the option any language in the filed Language. Thanks again

**Comment by joan-carles** [comment]
Hi, I have some additional information to provide you. First is the version 0.2.1 gives you much better results than 0.2 and the reason is the extra configuration parameter you added. So note that the option **interface language** in my case changes the searching results I obtain.

So the perfect configuration for me is next:

https://imgur.com/PtO52uC.png

Now there is just one thing "I don't like". When I use the configuration that works on my side for me I can't filter the results. So with the suitable config I can't see the options inside the circle:

https://imgur.com/pD3ZEwl.png

This options are quite useful to filter the results by date. So would be good to have the option to filter results. Other equivalents like Startpage or SearX offers this options.

Also let you know that Invidious discontinued his service.

**Comment by benbusby** [comment]
Hi, I just pushed a commit to the `dev` branch that addresses these issues. 

Regarding the filter by date, if you update your "Search Language" config, the date filter should appear. Alternatively, you can also append `:past <year|month|day|hour>` to the end of your search query to achieve the same effect.
