### ISSUE TITLE
[BUG] settings set by user stored globally 

### ISSUE THREAD

**Issue by fres7h** [benbusby/whoogle-search#179]
**Describe the bug**

settings applied by users are set/stored globally/persistently. 

**To Reproduce**

user changes setting, clicks apply. 
other user opens whoogle from different computer, browser, etc to find that setting applied by previous user has been set globally.

**Deployment Method**

manual build with run executable. 

**Version of Whoogle Search**

latest from source.

**Desktop (please complete the following information):**

any device

**Smartphone (please complete the following information):**

any device. 

**Additional context**
instance is public.
i've also noticed that this issue is not just affecting my instance, but other public instances as well.

mine: https://whoogle.himiko.cloud
other: https://whoogle.sdf.org

**Comment by benbusby** [comment]
Yeah this is a bit of a known issue. The intent for Whoogle was to only ever have individual instances rather than shared public ones, since public instances are incredibly easy for Google to rate limit or block altogether. Eventually I caved and added cookie based configs, with a "base config" that is used if cookies are unable to be set for some reason or are being blocked. Obviously something about this is broken and needs fixing, but figured context would be helpful here for why this is happening in the first place.

**Comment by fres7h** [comment]
i set the main config file to read only, i think it fixed it? not exactly sure. anyways, i love whoogle, and yeah i understand that it's not meant for public use.

thanks <3

**Comment by cybernats** [comment]
@fres7h did you made any customization related dark mode? i and he have got that problem https://github.com/benbusby/whoogle-search/issues/167 https://telegra.ph/file/70bf1f8ab3dd3e1efde7f.png but we don't see such issue on above your mentioned instances

**Comment by benbusby** [comment]
I *think* this can be closed now with the merging of #295 actually. Public instances can now set their own config settings on the backend and disable client side config changes. Config settings for users who have cookies enabled can also set session specific settings that shouldn't cause any global config changes.
