### ISSUE TITLE
New Deploy option i.e zeet.co

### ISSUE THREAD

**Issue by johntron8** [benbusby/whoogle-search#189]
@benbusby can you please make project deployable on an alternative platform i.e https://zeet.co
In their free plan 1 app deployment is free & also app doesn't sleeps as on heroku & replit.
Thanks

**Comment by benbusby** [comment]
From a quick glance, you should already be able to deploy it. They support deploying the app from a public Docker image. The basic steps to get it working should be:

1. Select deploy from Docker
2. Choose the `benbusby/whoogle-search` image
3. (Optional) Remove the predefined config volume (otherwise it won't be free)
4. Deploy

I didn't go through it myself since they require a credit card for the "free" tier. If someone else wants to go through this and verify that it works, I'll update the documentation.

**Comment by johntron8** [comment]
@benbusby I tested deploying Whoogle on zeet via docker image. All works good.

But found some minor issues in twitter redirection alternative. The mobile domain of twitter shows security error. Its due to mobile.twitter.com domain doesn't got redirected to nitter.net. it got reditected to mobile.nitter.net which is invalid. I think this issue is fixed in develop branch but haven't fixed on docker side.

Also sometimes when user searched an query & on results page when he trying to edit query sometimes the new query words didn't got typed in search bar. I tested this behavior on mobile, on desktop hasn't tested yet.

Also i need to know that changes you make here in develop branch are auto merged in Docker image ?
I mean is manual update required on zeet or it auto updates itself when changes detected in docker side.

**Comment by benbusby** [comment]
Sorry for the delay. Changes on develop are auto merged to the Docker image, so the `mobile.` prefix should be getting removed there as well. As a reminder, the `beta` tag is the image to use for the `develop` branch. The `latest` tag uses the `master` branch.
