### ISSUE TITLE
Option to have full width on search results 

### ISSUE THREAD

**Issue by Binyamse** [benbusby/whoogle-search#209]
Hello Whoogle team, loved the project and the idea, been using it for almost a month now without any issue, Thank you for this amazing tool. The only problem for me so far is the UI on the search result is discuraging to use the system, doesn't seem to be a modern tool. Is it possible to have a full-width page result instead of a small and centered page? Thanks.

**Comment by benbusby** [comment]
Since it's highly preferential, I'd rather not add in a specific config setting just for width. Eventually I'd like to support custom CSS theming, but not sure when that will be worked on.

That being said, you could use a browser plugin for applying specific CSS values to pages (I think DarkReader supports this, not sure what browser you're using though). The only setting you'd need is something like:

```css
body {
    max-width: 100% !important;
}
```

and that should accomplish what you're looking for.

**Comment by benbusby** [comment]
Since this has already been brought up before in #60, I'm going to close this one.
