### ISSUE TITLE
[BUG] <brief bug description>

### ISSUE THREAD

**Issue by Rekulous** [benbusby/whoogle-search#225]
Whoogle is telling me that unusual traffic is coming from my PC (I'm using a VPN) and I'm not getting a captcha to fix this. I am using Docker and this just started happening to me now.

1. Go to 'Whoogle from Docker using a VPN"
2. Search up something random
3. See error

My Deployment method was using Docker.

**Version of Whoogle Search**
Latest build from GitHub I think, I'm not so sure.

 - OS: Windows 10 
 - Browser: Brave 
- Version: Latest

**Additional context**
I was using Whoogle but then re-installed it.

Screenshot: 
![image](https://user-images.githubusercontent.com/79665689/111553377-a467bb00-875a-11eb-9ea3-71ca28a67d95.png)

**Comment by fres7h** [comment]
the IP your VPN is using is most likely blacklisted, so google's ratelimiting/blocking requests from it. this isn't a bug, this is just google being shit.

**Comment by benbusby** [comment]
Yeah, Google has gotten pretty aggressive with blocking VPNs lately it seems. Unfortunately the only foreseeable solution will be either #211 (which will mostly apply to publicly deployed instances) or deploying to an external server with lower traffic. The Heroku deployments seem to generally do pretty well with avoiding captchas, same with Repl.it, and I've had good luck with Whoogle instances running on Digital Ocean servers. 

Alternatively if your VPN provider allows it, you could try selecting a lower traffic server, since these occasionally are able to fly under the radar a bit better. Not ideal, but there's not a lot of other options.
