### ISSUE TITLE
[FEATURE] Perform searches based on browser language.

### ISSUE THREAD

**Issue by drugal** [benbusby/whoogle-search#249]
perform searches based on browser language.
Static browser preferences established by the administrator. I know whoogle was intended for personal use, maybe go a bit further?

**Comment by benbusby** [comment]
Sorry, I'm not sure what you mean. Do you mean querying for the user's browser language setting and updating the local Whoogle config for them? Since setting search language is already supported, is the benefit here just to automate that process?

**Comment by drugal** [comment]
Yes, that is exactly what I meant, being not expressing clearly, thank you

**Comment by benbusby** [comment]
I've thought this over a bit, and I don't think I want to add any more Javascript to the site than absolutely necessary. Since the site already supports alternative interface languages, I don't think adding more code to the front-end would provide enough value to make it worthwhile. I'm also planning on implementing #256 soon, which would supplement the existing language support as well.
