### ISSUE TITLE
Does pre-config apply to heroku deployment as that?

### ISSUE THREAD

**Issue by IniUe** [benbusby/whoogle-search#255]
hi, i have a question about heroku deployment.

https://github.com/IniUe/whoogle-search#environment-variables

`# You can set Whoogle environment variables here, but must set`
`# WHOOGLE_DOTENV=1 in your deployment to enable these values`
https://github.com/benbusby/whoogle-search/blob/develop/whoogle.env

Is it enough to remove # to enable that, or should i do something else to get that working?

Edit, when use quick deploy button then only appear line 4 to 13 in cofig vars (we cant do other configuration) then cant do anything for line 18 to 23 or can we add new config var after deployed app in heroku settings --> config vars?

**Comment by IniUe** [comment]
i dont mean about other configs below to it https://github.com/benbusby/whoogle-search/blob/develop/whoogle.env (hope may not misunderstand)

**Comment by neroichi** [comment]
I have same question. Need to activate dark theme and other configuration but still confused when deploying into heroku.

**Comment by benbusby** [comment]
The contents of `whoogle.env` won't be set for Heroku deployments, since the repo gets cloned for every deployment (but yes, removing the `#` would enable them for manual deployments).

The missing config vars on the Heroku deployment page is my fault though, I forgot to add them to `app.json`. I'll take care of that and update this issue once it's fixed.

**Comment by benbusby** [comment]
Okay, this should now be fixed as of b1c024f9e1172a69785b317fd04904fc0bda3234 for the `heroku-app-beta` deployments. The regular `heroku-app` deployments will see this change when release 0.4.0 is public.
