### ISSUE TITLE
[BUG] Text encoding problem in Simplified Chinese interface

### ISSUE THREAD

**Issue by ygsk10** [benbusby/whoogle-search#267]
**Describe the bug**

Japanese word showed in search result was wrongly encoded.

**To Reproduce**
1. Set `Interface Language` to `Simplified Chinese`
2. Search any Japanese keyword, such as `あなたの名前`
3. You'll find text like

```
キャスト: 監督・脚本：ロヘナ・ゲラ; 出演：ティロタマ・ショ�恁� ヴィヴェ�恁�・ゴ�恁螗啸� ギ�恁骏螗弗悭辍ぅ�ルカルニ��
```

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [x] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version v0.4.0
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium
 - Version: 88.0.4324.182

**Smartphone (please complete the following information):**
 - Device: 
 - OS: Android 11
 - Browser: Bromite
 - Version: 89.0.4389.117

**Additional context**

**Comment by ygsk10** [comment]
![Screenshot_20210406-164956](https://user-images.githubusercontent.com/82031146/113700023-24e56000-96f8-11eb-88d9-d13ed737827e.png)

**Comment by ygsk10** [comment]
It seems any phrase containing the `ー` is messed

**Comment by ygsk10** [comment]
![IMG_20210405_193251_695](https://user-images.githubusercontent.com/82031146/113702659-a094dc00-96fb-11eb-9e03-a54b443689fe.PNG)

**Comment by jacr13** [comment]
After investigating a bit, the problem is the random user-agent generated by whoogle, more precisely the "Mozilla" part.

Google seems to return the response with "charset=GB2312" when the Mozilla word is replaced by a random one and "charset=UTF-8" when Mozilla is provided.

To solve the problem a quick fix is to replace this line :
https://github.com/benbusby/whoogle-search/blob/d450cb1d616b6476afc4996c3aa9dfd8e1d15617/app/request.py#L52
by:
`mozilla = "Mozilla"`

**Comment by benbusby** [comment]
Weird. Thanks @jacr13 for looking into that, I'll push a hotfix soon.

**Comment by ygsk10** [comment]
Screenshot was deleted for it's exposing my private instance url
