### ISSUE TITLE
[FEATURE] Access website though proxy

### ISSUE THREAD

**Issue by DodyAlkarkhi** [benbusby/whoogle-search#276]
**Describe the feature you'd like to see added**
Sometimes websites block ip addresses especially if they get high traffic e.g Tor or VPN. Startpage (anonymous view) and Searx (mortyproxy) have a proxy option. I don't know if Whoogle supports this or not but I couldn't find it. So I would be grateful if something like this was introduced to Whoogle.

**Comment by DodyAlkarkhi** [comment]
https://github.com/asciimoo/morty

**Comment by benbusby** [comment]
Sorry @gripped, this seems to have gotten lost in my stream of notifications, I'm just now seeing your comment. 

Yes, I'm definitely interested in getting this implemented, but am curious what you had in mind for determining if morty is available on a user's Whoogle instance. Are you thinking it would just be a configurable setting in the same vein as the privacy frontend settings (i.e. the `WHOOGLE_ALT_[MD|RD|IG|etc]` vars)? If that's the case, I assume enabling morty for in-app result views would require that environment variable to be set? 

I guess my main priority is ensuring that this gets implemented as agnostic as possible (not being dependent on an external proxy). It should be easy enough to allow proxying directly through Whoogle by modifying the existing NoJS option a bit, but could also allow configuring an external proxy (like morty) as an add-on. So in my head, implementing this feature completely would mean:

- A config setting for enabling website access through app proxy
- An environment variable to allow querying through an external service -- if not set, then results are proxied through Whoogle itself
    - Could be either a full URL or a path if hosted parallel to Whoogle
- Potentially removal of (or reconsideration of how to enable) the NoJS feature itself. I'm hesitant to have multiple links for both viewing a NoJS link and accessing a result through a normal/non-sanitized proxy.

Feel free to open a draft PR with your current progress if you want my input before it's ready, otherwise just keep me posted.

**Comment by gripped** [comment]
> Sorry @gripped, this seems to have gotten lost in my stream of notifications, I'm just now seeing your comment.

No problem at all. I have Morty working for me with Whoogle. There's no rush.

In my ideal world I think Whoogle would offer:

- A link to normal results which will be fetched directly by the users browser (**It does now**)
- A proxy link which delivers the user the page hiding the the users home IP address from the server (Unless they are hosting on a home IP) with the following mutually exclusive choices 
   - Unchanged page, just proxied.
   - Proxied page sanitized of javascript (**It does now** NoJS)
   - An external proxy like Monty with the proxy part of the URL defined by an environment variable.

Your comment from another issue:
#508

> I think it would probably get used a lot more if it was refactored to serve as a general website proxy feature that allowed users to open a result in Whoogle itself (using the same /window route), and conditionally enable/disable Javascript depending on user preference.

So I think we are thinking along the same lines ?
As for the configuration page I guess one option along the lines of 'Show proxy link'.
And then a three state radio button to select the type of proxying ?

I'll see what I can come up with. But don't hold your breath.
I do not consider myself a programmer in the least. I like playing around with it all though and occasionally I succeed. 
If you decided to jump in and just do it I would not be in the least bit miffed. Probably more relieved.

**Comment by benbusby** [comment]
> So I think we are thinking along the same lines ?
As for the configuration page I guess one option along the lines of 'Show proxy link'.
And then a three state radio button to select the type of proxying ?

Yep, sounds like we're on the same page. The only catch I think is that if the user doesn't have the external proxy URL configured, that the external proxy option is disabled somehow. There's similar behavior with the Tor config option when the user's machine doesn't have Tor running. 

> I'll see what I can come up with. But don't hold your breath.
I do not consider myself a programmer in the least. I like playing around with it all though and occasionally I succeed.
If you decided to jump in and just do it I would not be in the least bit miffed. Probably more relieved.

Well I'd still like to encourage you to give it a shot! I'll hold off on implementing anything on my end. If you end up opening a PR that still needs work, I'm happy to jump in at that point (if needed).

**Comment by gripped** [comment]
> The only catch I think is that if the user doesn't have the external proxy URL configured, that the external proxy option is disabled somehow.

Yeah I had thought of that but forgot to mention. Environment variable defined = Three choices . Not defined = 2 choices and one greyed out.

> Well I'd still like to encourage you to give it a shot!

It's gonna be a longshot! ;) 
I am going to try. Mainly by copying your code wherever possible.

**Comment by DUOLabs333** [comment]
Doesn't Whoogle already have proxy support (it should support whatever proxies `requests` support)?

**Comment by benbusby** [comment]
@DUOLabs333 this is a bit different. In this case what's being asked for is to view result webpages through Whoogle itself. So a user would be given a "View Result in Proxy" option next to each result, and if clicked, the result page would be loaded as `https://whoogle-instance.com/result?page=example.com`, where `example.com` is presented to the user through Whoogle itself. 

@gripped did you end up looking into this? No worries if not, just curious :)

**Comment by DUOLabs333** [comment]
@benbusby Oh, ok. Does the link have to be under the whoogle domain, or can the proxy be on some other domain?

**Comment by benbusby** [comment]
I believe the desired effect is for the request to be proxied by the same whoogle instance that provided the results.

**Comment by gripped** [comment]
> @gripped did you end up looking into this? No worries if not, just curious :)

@benbusby I did, but failed :) Decided to take a break and come back to it. Then life got in the way (I've been at version 0.60 until minutes ago.)

**Comment by gripped** [comment]
@benbusby
I've hacked morty into my instance again. I still prefer how morty works. But I consider this a personal hack
```
--- results.py.bak	2022-06-06 10:42:57.000000000 +0000
+++ results.py	2022-06-06 11:53:35.755138670 +0000
@@ -206,11 +206,8 @@
     av_link = BeautifulSoup(features='html.parser').new_tag('a')
     nojs = 'nojs=1' if config.nojs else 'nojs=0'
     location = f'location={result["href"]}'
-    av_link['href'] = f'{Endpoint.window}?{nojs}&{location}'
-    translation = current_app.config['TRANSLATIONS'][
-       config.get_localization_lang()
-    ]
-    av_link.string = f'{translation["anon-view"]}'
+    av_link['href'] = '/morty/?mortyurl=' + result['href']
+    av_link.string = ' Proxied'
     av_link['class'] = 'anon-view'
     result.append(av_link)
```
Only sharing for the benefit of anyone else who might wish to the same. Which is probably a total of zero people?
