### ISSUE TITLE
[FEATURE] Replace G Maps with OpenStreetMap

### ISSUE THREAD

**Issue by askabaz22** [benbusby/whoogle-search#284]
Can we have a replacement for Google Maps link? I'm referring especially to the"Maps" function in the bar under the search field, I think it would be very useful

**Comment by benbusby** [comment]
This has come up a few times before. OpenStreetMap doesn't provide 1-to-1 link parity between Google Maps and their service, so it unfortunately isn't a viable alternative. There would need to be development of a separate "OSM link conversion" tool for the app, which would need to be separate from Whoogle. 

If you're meaning just changing the "Maps" button to take you to OSM instead of Google Maps, that's technically doable, but would be confusing from a UX perspective (since direction and business location links in search results would still go to G Maps).
