### ISSUE TITLE
[BUG] Docker shows container as “Unhealthy”

### ISSUE THREAD

**Issue by r0arkin** [benbusby/whoogle-search#287]
After the most recent updates (I believe the last 3 commits), Docker again shows the container as "Unhealthy". Below is the health check.

```
{"Status":"unhealthy","FailingStreak":98,"Log":[{"Start":"2021-04-13T08:56:44.730335835-07:00","End":"2021-04-13T08:56:44.949223012-07:00","ExitCode":1,"Output":""},{"Start":"2021-04-13T08:57:15.500682888-07:00","End":"2021-04-13T08:57:15.707056244-07:00","ExitCode":1,"Output":""},{"Start":"2021-04-13T08:57:46.275134217-07:00","End":"2021-04-13T08:57:46.495521038-07:00","ExitCode":1,"Output":""},{"Start":"2021-04-13T08:58:17.077553245-07:00","End":"2021-04-13T08:58:17.294039045-07:00","ExitCode":1,"Output":""},{"Start":"2021-04-13T08:58:47.906687469-07:00","End":"2021-04-13T08:58:48.130840141-07:00","ExitCode":1,"Output":""}]}
```

**Comment by benbusby** [comment]
That's strange. Nothing has changed about the Dockerfile since the update to fix the healthcheck in the first place. It's also odd that it's not actually providing any error message in the output (i.e. `"ExitCode":1,"Output":""`), which sort of makes it hard to debug the problem. I'll try to look into this more later.

**Comment by r0arkin** [comment]
Okay so I figured it out. I just deleted the image and re-downloaded and everything started working again....gremlins.

**Comment by Pofilo** [comment]
I have exactly the same problem on 0.4.1 (Digest:sha256:f168190128825725c5aae37dee99349257fead852d265dca18ecb0046e376986).

When I do:
```
wget -qO- --no-verbose --tries=1 http://localhost:${EXPOSE_PORT}/ || exit 1 # with EXPOSE_PORT at 5000
echo $?
```
I have the expected result 0.


However, when I check `docker inspect --format='{{json .State.Health}}' whoogle-search`

The ExitCode is 1 and the output:
```
"Output":"index.html: Read-only file system\nCannot write to ‘index.html’ (Read-only file system).\n"
```

Okay, I just figured out it's already fixed with: https://github.com/benbusby/whoogle-search/commit/cb80c181a6129459a6aeae61e882580c0f7ac084

Thanks ^^
