### ISSUE TITLE
[QUESTION] IP address query 

### ISSUE THREAD

**Issue by milachevalier** [benbusby/whoogle-search#294]
This is just a random thing that popped into my mind.

When you usually google "my ip" there is a snippet on top of the results page that shows the current IP address. When you search that on whoogle, nothing shows up. Is that a limitation from google?

Was just curious in finding out from which IP results are fetched from google. Heroku normally has a pool of ip addresses.

**Comment by benbusby** [comment]
Hmmm, looks like that's a (new) limitation from google. I recall at one point the first search result was still the instance IP, but something must have changed since then. 

Let me know if you think it'd be worth the effort to include a resource for displaying the IP of the current instance. I suppose it could be useful for the sake of satisfying curiosity...but not sure if there's utility beyond that.

**Comment by milachevalier** [comment]
The question itself was just for the sake of satisfying curiosity, so please don't go through the trouble. :) Thanks!
