### ISSUE TITLE
[FEATURE] Include category tabs (all/images/news/etc) in header

### ISSUE THREAD

**Issue by unixfox** [benbusby/whoogle-search#298]
**Describe the bug**
The image tab has a different layout (CSS?) from the other tabs like "all", "videos", "news". The text of the menu is bigger on the image tab.
Moreover, in the image tab I'm not able to access maps nor books, those links aren't displayed.

![image](https://user-images.githubusercontent.com/4016501/115998392-83567d80-a5d6-11eb-8e41-c184a4d1348f.png)
![image](https://user-images.githubusercontent.com/4016501/115998404-95382080-a5d6-11eb-89b7-2280c621e16e.png)

Is this intended? It's a bit disturbing to have a sudden change of layout like this.

**To Reproduce**
1. Do a search.
2. Click on the "image" link in the menu.
3. See different layout from the previous page

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [x] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Firefox
 - Version: 88.0 (64-bit)

**Additional context**

**Comment by benbusby** [comment]
It's not necessarily "intended", but is an inadvertent side effect of using Google's non-Javascript search query. For some reason the default styling on the image page is just different. Very little styling (outside of color theming) is performed by Whoogle. 

I agree that it's a bit jarring, though. I think the best solution at the moment would be to include the category tabs in `header.html` and remove them when parsing the results in the Whoogle filter. There would need to be some coordination with #256 though, since otherwise the category tab titles would not reflect the user's preferred language on search results.

**Comment by benbusby** [comment]
Note that this should also include language selection and time filtering, as noted in #524.
