### ISSUE TITLE
Move to a better place!

### ISSUE THREAD

**Issue by soheilkhanalipur** [benbusby/whoogle-search#314]
Unfortunately, I have to say that you have put this program in a bad place! GitHub!
This app deserves places like: Codeberg, Gitea, GitLab (Instances), and wherever better…
GitHub boycotts users, removes apps, and actually says "Whatever I want is going to be saved and whatever I don't need Is going to be deleted." The app has not paid attention to users' requests for RTL support for years, and says this is not a priority!
Free software should be free somewhere, which GitHub does not have!
Aren't these enough to leave GitHub?

**Comment by grubeli** [comment]
I think Codeberg or another alternatives are good places but big downside is that Whoogle will get much less development support due to most of people is familier, have accounts and prefer to work on Github.
Maybe middle ground would be to setup a mirror at Codeberg (my fav) and specify at Readme.md that code is also located at codeberg.
If Github decides to remove the repo we can easily move to codeberg,etc.

**Comment by soheilkhanalipur** [comment]
Yes that's right; But you must start somewhere to get anywhere! (Revolution must start from somewhere!)

**Comment by itsnotsaved** [comment]
yep; that's good to mirror for now (as i know some services support auto sync from origin repo eg: gitlab)
or if @benbusby doesn't expect considerable dev support (as i see also he doesn't care about that) then able to move.

**Comment by benbusby** [comment]
I’m happy to mirror the repo anywhere else. The unfortunate reality that @grubeli mentioned is how ubiquitous GitHub is. Whoogle was actually originally hosted on GitLab for months, but practically nobody ever found the repo. As soon as I moved it to GitHub it got exponentially more attention, which was nice since I wanted feedback on the project. Now that there’s a general awareness of the project, however, I’m happy to set up mirrors elsewhere and mention them in the readme.

> as i see also he doesn't care about that

Not sure where you got this from. I’ve been fairly vocal in a lot of issues about how I’d love more community support and that I value any and all contributions. 

In any case, I’ll start setting up mirrors for now and update the readme.

**Comment by soheilkhanalipur** [comment]
You're Great! Thank You! Hoping for better program progress.

**Comment by gripped** [comment]
> Not sure where you got this from.

I can only guess it's due to you having a few well deserved days away from the project, for whatever reason, they are all valid.

I dip into many of the issues on this repo, and have been involved in my own small way myself.
You are I think almost a model in how to engage with a community. Patient, open, and both pro and reactive.

I post this only because it may be disheartening, to you, to read such unnecessary negativity, though it may not have been meant in the way it came across ?

For the record personally I like Github. I've used many of the others and prefer Github overall. Though familiarity probably plays a large part ?

Keep up the good work.

**Comment by benbusby** [comment]
Thanks for the kind words @gripped, I really appreciate it and your involvement with the project.
