### ISSUE TITLE
[QUESTION] How are the build triggers configured?

### ISSUE THREAD

**Issue by mrckndt** [benbusby/whoogle-search#335]
Hi,
May i ask how the build triggers are configured on hub.docker.com? Which tag should i use when i want to stay on the latest stable release? 'latest' was rebuilt 17h ago (like 'beta' and '0.5.2') but it's still pointing to version 0.5.1.

Thanks in advance.

**Comment by benbusby** [comment]
The `latest` tag is built on every push to the `main` branch, while the `beta` and `buildx-experimental` tags are built on every push to the `develop` branch. You should be using the `latest` branch -- can you elaborate what you mean by it still pointing to version 0.5.1? Are you seeing the old version number in the UI on that tag? Or is the bug that was fixed in 0.5.2 still appearing for you?

**Comment by mrckndt** [comment]
Thank you for the explanation about the branches.

> Are you seeing the old version number in the UI on that tag?

Yes, its version is '0.5.1' and i thought `latest` should be the same as the `0.5.2` tag.

**Comment by benbusby** [comment]
Hmmm...on my end I'm seeing the new version number correctly on the `latest` tag. I just triggered another build manually for that tag just for good measure -- try that out whenever you have a chance and let me know if it's working for you.

**Comment by benbusby** [comment]
I assume this is fixed now, but feel free to comment again if you're still seeing the old version on the `latest` tag.

**Comment by mrckndt** [comment]
FYI it's working now after deleting the old images. Maybe this was a Docker hiccup on my side :shrug:
