### ISSUE TITLE
[BUG] After updating to v.0.5.3, search defaults to "Search English pages"

### ISSUE THREAD

**Issue by edo0** [benbusby/whoogle-search#347]
**Describe the bug**
After updating to v.0.5.3 on Heroku, search results default to "Search English pages", instead of searching results in any language. This, in spite of no variable being set in the configs for search language.
I have also tried deleting and re-deploying the app, but to no avail unfortunately

**To Reproduce**
1. Deploy on Heroku
2. Search anything
3. "Search English pages" will be automatically selected
(If I open configs from my whoogle homepage, the search language field is indeed empty as intended)

**Deployment Method**
- [X] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [e.g. Arch Linux]
 - Browser [e.g. Firefox, Qutebrowser (QTWebEngine]
 - Version [e.g. latest]

**Comment by edo0** [comment]
Ok, I have worked out the solution: one should configure the variable `WHOOGLE_CONFIG_SEARCH_LANGUAGE` as `""`, rather than an empty space.
I must say this does not seem very intuitive to me, as I would expect that not setting any language would revert to "search pages in any language".
Nor it is mentioned here ([https://raw.githubusercontent.com/benbusby/whoogle-search/develop/app/static/settings/languages.json](https://raw.githubusercontent.com/benbusby/whoogle-search/develop/app/static/settings/languages.json)) that `{"name": "-------", "value": ""} ` would allow the search to include any language.
Please consider reverting to the previous set up, or allow to make it clearer, as being able to search pages in any language is pretty much essential for any bilingual individual

**Comment by accountForIssues** [comment]
Same issue with different solution.

#### Raspberry Pi-4 w/ docker using `whoogle-search:buildx-experimental`
using `WHOOGLE_CONFIG_SEARCH_LANGUAGE=""` 🚫 defaults to english
using `WHOOGLE_CONFIG_SEARCH_LANGUAGE=" "` ✅  shows all results

#### Fly.io instance w/ docker using `whoogle-search:latest`
using `WHOOGLE_CONFIG_SEARCH_LANGUAGE=""` 🚫 
using `WHOOGLE_CONFIG_SEARCH_LANGUAGE=" "` 🚫 
not setting `WHOOGLE_CONFIG_SEARCH_LANGUAGE` 🚫 

#### Fly.io instance w/ docker using `whoogle-search:0.5.3`
using `WHOOGLE_CONFIG_SEARCH_LANGUAGE=""` 🚫 
using `WHOOGLE_CONFIG_SEARCH_LANGUAGE=" "` ✅ 

I agree with @edo0 that search results should default to all languages unless specified by the user.

**Comment by benbusby** [comment]
The issue with defaulting to "all languages" is that Google falls back to using IP geolocation to determine the relevant language, which sometimes breaks functionality for users who don't speak the language native to the country that the server for their instance is using. The fallback from "any" to "english" default was added by request in #344, where the user wasn't able to understand their search results because the results were being returned in German when using a German VPN (and leaving the language setting on the default value). 

I'll roll back the change for now and be clearer about setting interface language in scenarios where IP geolocation is being applied behind the scenes, but it doesn't seem like there's a solution that makes everybody happy.

**Comment by benbusby** [comment]
Default language reverted in `0.5.4`, Docker images will be updated when the builds finish.

**Comment by edo0** [comment]
Thank you very much!
