### ISSUE TITLE
[BUG] Tor can't show up any search result

### ISSUE THREAD

**Issue by LorisTecnology** [benbusby/whoogle-search#354]
**Describe the bug**
I can't bypass captha check

![image](https://user-images.githubusercontent.com/63395247/121514886-cf297e80-c9ec-11eb-8e07-cf1e34f50175.png)

**Comment by benbusby** [comment]
Google often blocks connections from Tor, and there isn't a way to bypass captchas through Whoogle (there might be a solution with #211, but there's no timeline on when this will be done and would only affect public instances that opt-in -- which would likely be very few).

I'd recommend using a VPN instead of Tor, since they are far less likely to be blocked.

**Comment by shayaknyc** [comment]
Forgive me, I came across this issue when searching for TOR and Whoogle in a docker-container. TOR runs just fine and gets 100% bootstrapped, but anytime I make a search request with "use tor" turned ON, it just times out. I don't even get a captcha. The logs don't seem to show anything useful. Does this mean that routing google search requests through TOR in the docker container just doesn't work?
