### ISSUE TITLE
[QUESTION] How to make the website public?

### ISSUE THREAD

**Issue by muzihuaner** [benbusby/whoogle-search#421]
How to make the website public? Let different users use different configurations instead of the same configuration

**Comment by benbusby** [comment]
Currently different users will have their configuration settings stored using cookies, and users with cookies blocked will share the same config. Ultimately though the project isn't intended for multiple users, since this usually results in the instance getting blocked by Google. I'd recommend just setting up a public instance with all of the configuration settings predetermined using environment variables, and then disable client side config changes using `WHOOGLE_CONFIG_DISABLE=1`.
