### ISSUE TITLE
[BUG] When I search for "something -site:anysite" the "-site:anysite" part disappears from the search bar

### ISSUE THREAD

**Issue by DodyAlkarkhi** [benbusby/whoogle-search#424]
**Describe the bug**
When I search for "something -site:anysite" the "-site:anysite" part disappears from the search bar but still shows results for that search query.

**To Reproduce**
1. Search for whoogle -site:reddit.com
2. See search bar for bug

**Deployment Method**
- [x] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version v0.5.4
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 92.0

**Comment by benbusby** [comment]
This is currently intentional behavior, since the comma separated site blacklist that can be configured per instance uses the same `-site:<sitename>` syntax, and can render search queries unreadable if there are more sites blacklisted. I'm open to potential improvements, but it isn't a bug necessarily.
