### ISSUE TITLE
[QUESTION] Why does a search query expiry when I move back to that page?

### ISSUE THREAD

**Issue by arunsathiya** [benbusby/whoogle-search#442]
When I make a search on Whoogle and visit a result, and when I move back to Whoogle using the back button on my browser, I see a message that the document has expired. It reads:

```
Document Expired

This document is no longer available.

The requested document is not available in Firefox’s cache.

    As a security precaution, Firefox does not automatically re-request sensitive documents.
    Click Try Again to re-request the document from the website.
```

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/18581859/135048452-503958b3-77f5-4aa6-b4ad-a0f3de2acfe4.png">

Is this something to fix within Whoogle or something to do with my browser?

**Comment by Stolz** [comment]
For privacy reasons, by default Whoogle uses `POST` HTTP method to send the search requests. That way, your search terms are sent in the HTTP request body instead of the HTTP request URL. Usually the request URL ends up in the web server logs and in the browser historic records whereas request body does not. Hence using `POST` method gives you more privacy.

By default, Firefox (and other browsers) will refuse to reload pages that originated from a `POST` HTTP request, hence the error you are seeing.

You can configure Whoogle to use `GET` HTTP method instead of `POST`, which will give you less privacy but it will avoid the `Document Expired` message. To do so, simply set `WHOOGLE_CONFIG_GET_ONLY=1` config option.

**Comment by arunsathiya** [comment]
Thanks for sharing this, @Stolz! I'll leave things as they are now.

**Comment by diogogmatos** [comment]
Hey, sry for bothering but I've been searching everywhere and I just can't figure out how to `"set WHOOGLE_CONFIG_GET_ONLY=1"`. I know you need to use `whoogle.env` file and uncomment that setting, I've done that. What I can't seem to do is `"set WHOOGLE_DOTENV=1"` to enable the use of whoogle.env. What does "set" mean? How do I "set" that variable? Should I add something to the `whoogle.service` file? HELP (I'm running whoogle locally)
