### ISSUE TITLE
[FEATURE] Logging

### ISSUE THREAD

**Issue by DUOLabs333** [benbusby/whoogle-search#458]
Is it possible to write all search queries to a file somewhere?

**Comment by benbusby** [comment]
No, this functionality doesn't exist in Whoogle, and won't since it's a prime target for abuse of privacy. That being said, it'd be pretty easy to take the contents of a search and dump them to a file, but I won't walk through how to do that here, and would highly discourage that unless there's a legitimate reason.

**Comment by DUOLabs333** [comment]
I actually say that, because I'm running whoogle for myself same-device, so it would be nice if I could have a log. But I understand.
