### ISSUE TITLE
[BUG] Whoogle service not starting

### ISSUE THREAD

**Issue by xXWhacker** [benbusby/whoogle-search#514]
I just installed a fresh copy of Manjaro Plasma and switched it to the testing branch and after installing Whoogle and after enabling and starting it's service I check it's status and get the below. Other than this I'm not seeing any other issues with Manjaro or other apps I've already installed. Any idea what's going on? Thanks

```
    ~  sudo systemctl status whoogle                                               ✔ 
[sudo] password for whacker: 
● whoogle.service - Whoogle
     Loaded: loaded (/usr/lib/systemd/system/whoogle.service; enabled; vendor preset: disa>
     Active: activating (auto-restart) (Result: exit-code) since Sun 2021-10-31 11:21:19 P>
    Process: 3286 ExecStart=/opt/whoogle-search/venv/bin/python -um app --host $BIND_ADDRE>
   Main PID: 3286 (code=exited, status=1/FAILURE)
        CPU: 228ms
lines 1-6/6 (END)

```

**Comment by benbusby** [comment]
Seems to be an issue with Manjaro/Arch, as reported in #476 and #488. 

Are you using pip to install whoogle? If so, could you try using [the test release for the app](https://test.pypi.org/project/whoogle-search/) to see if it fixes your problem? It seems unlikely, but worth a shot. If that does work, feel free to reopen this issue, since that would indicate to me that it's a Whoogle-specific problem that I can fix.
