### ISSUE TITLE
[FEATURE] If full URL entered in search it's treated as such

### ISSUE THREAD

**Issue by thunderclap82** [benbusby/whoogle-search#526]
I have Whoogle set up as my browser start page. When opened, the cursor starts in the Whoogle search bar. It would be nice if a URL is entered, without or without http/s, it would just go to that site instead of searching for it. It would reduce an extra step of clicking in the browser URL bar first.

**Comment by benbusby** [comment]
I'm not sure I'm comfortable implementing this, since it breaks expected behavior for most (all?) search engines. I do appreciate the consideration though. Personally I'm accustomed to just hitting ctrl+L (or cmd+L) to move the cursor to the search bar if I want to navigate directly to a site instead of searching.

**Comment by thunderclap82** [comment]
I didn't even consider the Ctl-L option. I'll just start doing that. Thanks!
