### ISSUE TITLE
Error deploying container  [Errno 1]

### ISSUE THREAD

**Issue by MrPrr0** [benbusby/whoogle-search#529]
Hi all,

I just try to deploy this container a run on this issue

Fatal Python error: pyinit_main: can't initialize time

Python runtime state: core initialized

PermissionError: [Errno 1] Operation not permitted

Any help?

**Comment by benbusby** [comment]
Sounds like you might be using `docker-compose` on a Raspberry Pi, which you could've included in the bug report template for the repo. 

In any case, it looks like the solution for that issue is here: https://github.com/linuxserver/docker-papermerge/issues/4#issuecomment-735236388 (not a Whoogle issue).
