### ISSUE TITLE
[BUG] Firefox search bar just redirects me to the Whoogle homepage

### ISSUE THREAD

**Issue by edmael** [benbusby/whoogle-search#54]
**Describe the bug**
When I search on my self-hosted Whoogle using Firefox bar the results is the homepage of my Whoogle instance rather than actual result page.

**To Reproduce**
1. Add Whoogle to your search engine by clicking on the three dots in Firefox address bar
2. Search something with the new added engine
3. See error

**Expected behavior**
I expect to see the actual results of my query, not the Whoogle homepage.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox (both stable, nightly and beta)

**Additional context**
On my mobile phone everything works as expected: it seems the destkop version forgets the %s.

**Comment by benbusby** [comment]
How is your instance deployed (ie Heroku, reverse proxy, etc)? On desktop, search is generally done via POST request, so there shouldn’t be the %s url query parsing. 

Can you try switching your config to “GET requests only” and see if that fixes it? You’ll likely need to remove the search template from Firefox on your desktop and re-add it after changing the config.

**Comment by benbusby** [comment]
For added clarification, are you using the latest version of the master branch? I'm a bit confused, as I use Firefox for my desktop as well and am running the app fine. There are also tests in place to ensure this functionality works properly, unless there's something wrong with the opensearch template...which also seems unlikely, as I just went through and verified them on my end.

**Comment by edmael** [comment]
Ok, setting "GET request only" fixed the problem for me even on the destkop, guess it was just that.
Running with docker-compose using the standard options and nothing else, the only thing that MAYBE can cause some problem is that I avoid exposing directly the docker port but I use a "master" nginx reverse proxy that expose all my services.

My whoogle.subdomain.conf is like this:

`server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name search.*;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app whoogle-search;
        set $upstream_port 5000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}`

**Comment by benbusby** [comment]
So I looked into this a bit more, and discovered some language regarding `301` code redirects to HTTPS that I wasn't aware of before, namely that in the [method description](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections) it states:

> GET methods unchanged.
Others may or may not be changed to GET.

So it looks like it's just a matter of using `308` redirects instead, and explains why the POST search requests are working for some and not others. Should be easy enough, I'll push a fix soon.

**Comment by benbusby** [comment]
Ok, fixed in latest master now. If you're not letting Flask handle protocol redirects for you though, then it might be an issue with wherever you're setting redirects in your nginx config. If you have a `301` redirect in place somewhere else (i.e. `return 301 https://$host$request_uri;`) then that will need to be upgraded to use `308` as well in order to keep POST requests from changing to GET requests.

**Comment by alex-phillips** [comment]
I'm getting this same issue. Using latest docker image, same compose file as in the repo, behind an reverse nginx proxy using HTTPS. One added on Firefox desktop, all search bar requests just take me to the home page.

As I said, running in docker. Using Firefox desktop on Ubuntu 20.04.

**Comment by LivingWithHippos** [comment]
I also have this issue. I think firefox is the problem since I can correctly use POST and GET from the page. The search bar plugin  is provided by https://github.com/benbusby/whoogle-search/blob/develop/app/templates/opensearch.xml 

The culprit is this line

```
  <Url type="text/html" method="{{ request_type }}" template="{{ main_url }}/search">
    <Param name="q" value="{searchTerms}"/>
  </Url>
```
that I changed to

`<Url type="text/html" method="get" template="{{ main_url }}/search?q={searchTerms}"/>`

as a temporary fix. All the searches from the bar will be with a GET method, but if you directly go to your website it will still be POST (or whatever you selected). 
I didn't check autocomplete since I don' t use it but it should be similar. 
I didn' t make a PR since I don' t think this is the best way.

If you like me want to test this in your existing docker container you can run bash on it
`docker exec -it your_whoogle_container /bin/bash` and edit (I installed nano with `apt-get install nano`) the file opensearch.xml under app/templates, then restart the container with 'docker restart your_whoogle_container'. You can check if it got loaded by going to `whoogle-domain.whatever/opensearch.xml`.
Remember to remove and re-add the whoogle search from Firefox settings or you'll keep the old one.

**Comment by benbusby** [comment]
I'm curious, are either of you using an older or beta version of Firefox? The majority of Firefox users I've spoken recently with haven't encountered this issue, and neither have I, but I'm running `77.0.1` without any opensearch issues. The fix mentioned above is how Firefox's internal parsing of the opensearch template *should* be functioning from their end -- the nested `Param` tag should get parsed to `/search?q={searchTerms}"` if using a GET method, otherwise the search term is POSTed to the server. 

I'd be curious to see a server log capture from when the search bar is redirecting to the home page, and see if it's a `302` redirect or just a `200` (which would indicate that Firefox likely isn't sending the actual search term to the `/search` route).

**Comment by LivingWithHippos** [comment]
No, I' m on latest too. Also didn' t work on android.
NGIX access.log

original opensearch, I think this was a search from the bar + one on the page

```
my-ip - - [24/Jun/2020:10:10:18 +0100] "POST /search HTTP/1.1" 301 169 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:10:10:18 +0100] "GET /search HTTP/2.0" 302 209 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:10:10:18 +0100] "GET / HTTP/2.0" 200 5197 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:10:10:19 +0100] "GET /config HTTP/2.0" 200 133 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:10:10:21 +0100] "GET /opensearch.xml HTTP/2.0" 200 857 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:10:11:36 +0100] "POST /search HTTP/1.1" 301 169 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:10:11:37 +0100] "GET /search HTTP/2.0" 302 209 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:10:11:37 +0100] "GET / HTTP/2.0" 200 5197 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:10:11:37 +0100] "GET /config HTTP/2.0" 200 133 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
```

With my modification

```
my-ip - - [24/Jun/2020:18:44:04 +0100] "GET /search?q=apply+docker+voklume+edits HTTP/1.1" 301 169 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:18:44:05 +0100] "GET /search?q=apply+docker+voklume+edits HTTP/2.0" 200 11000 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:18:44:05 +0100] "GET /static/js/autocomplete.js HTTP/2.0" 200 3860 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:18:44:05 +0100] "GET /static/css/search.css HTTP/2.0" 200 640 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:18:44:05 +0100] "GET /static/css/header.css HTTP/2.0" 200 1061 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
my-ip - - [24/Jun/2020:18:44:05 +0100] "GET /static/img/favicon.ico HTTP/2.0" 200 1150 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"
```

**Comment by alex-phillips** [comment]
Same. Using 77.0.1 with the latest whoogle docker container. It's worth noting that this _was_ working for me at one point.

**Comment by alex-phillips** [comment]
@benbusby Upgraded to FF 78 and still have this issue.

**Comment by clarkdave** [comment]
Same issue here.

- Firefox 79
- Latest Whoogle docker with standard settings
- Running behind nginx via https

After adding Whoogle as a Firefox search provider, any search result just goes to the Whoogle homepage. Here's my nginx log:

```
86.26.240.135 - - [06/Aug/2020:13:02:27 +0000] "POST /search HTTP/1.1" 301 170 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0"
86.26.240.135 - - [06/Aug/2020:13:02:27 +0000] "GET /search HTTP/1.1" 302 209 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0"
86.26.240.135 - - [06/Aug/2020:13:02:27 +0000] "GET / HTTP/1.1" 200 5245 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0"
86.26.240.135 - - [06/Aug/2020:13:02:27 +0000] "GET /config HTTP/1.1" 200 148 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0"
```

**Comment by PlutoHDDev** [comment]
Hello, have you found a solution to this problem? I have the same problem with Firefox 98.0.2 and a fresh Whoogle installation behind a Nginx proxy. I'm very enthusiastic about Whoogle, but if it doesn't work as a default search engine, then it's hard to use.

**Comment by ludoctl** [comment]
+1 here as I've just met the issue on FF 98.0.2 (64-bit) on Ubuntu. My setup works fine as default on my Android's Firefox Focus...

**Comment by GabrieleV** [comment]
Same problem here: docker behind an apache reverse proxy with https and http to https redirect.
How to solve ?
