### ISSUE TITLE
Autocomplete - would be nice.

### ISSUE THREAD

**Issue by elvirmuslic** [benbusby/whoogle-search#56]
Autocomplete - It would be nice. I'm not sure that it is possible to pass queries like that as well as completes but would be a great feature to have.

**Comment by benbusby** [comment]
AFAIK, there isn't an open source search autocomplete library out there. This would require paying a company for access to their autocomplete API, which isn't a feasible addition to the project since instances are primarily self hosted. If someone knows of an alternative and comes across this issue, feel free to reopen.

**Comment by gripped** [comment]
https://github.com/asciimoo/searx/blob/master/searx/autocomplete.py

Might be worth a look ;) Doesn't look that complex but then I can't program.

**Comment by elvirmuslic** [comment]
@benbusby @gripped This uses Google API.  
However, Ben I don't see it being limited or found that it is a paid service. 

The Google **Maps** Autocomplete Search is, we are not using Maps.

**Comment by elvirmuslic** [comment]
> 
> 
> https://github.com/asciimoo/searx/blob/master/searx/autocomplete.py
> 
> Might be worth a look ;) Doesn't look that complex but then I can't program.

Thank you gripped, this might be just what we needed, as I am not a javascript developer I will not try implementing this feature unless there is no one else to do it then I will come up with something.
