### ISSUE TITLE
[Question] Two questions about Whoogle: Privacy and a public instance

### ISSUE THREAD

**Issue by mendel5** [benbusby/whoogle-search#59]
Hi @benbusby,

Thank you for creating Whoogle! It's really cool and I like to use it.

I have two questions about Whoogle regarding privacy and the availability of a public instance.

### 1. Privacy

I was wondering how you get the data from the Google search results page to my local machine. As far as I understand [this line in request.py](https://github.com/benbusby/whoogle-search/blob/a4382d59f67a3f354c0bbb3fdffaf7792aba4f3f/app/request.py#L77) sends a request to the Google servers.

So when I search for something, Google can still see the metadata of my search, e.g. my search terms, my IP address, my request time, etc., right?

### 2. Public instance

As far as I know there is currently no public instance of Whoogle. In the README.md it also says this:
"Whoogle is intended to only ever be deployed to private instances [...]".

What's the reason for this?

Maybe you can operate a public instance so people can get a first glimpse of Whoogle.

Thanks

**Comment by eoopx** [comment]
@mendel5 good idea, suggest @benbusby to host public instance using good server provider. furthermore, you can ask people to donate and sponser from bitcoin or whatever for keep it up. there're some providers accept btc as well.

**Comment by benbusby** [comment]
Hey @mendel5, thanks for checking out Whoogle. 

Re: **Privacy**
The app works like so:
```
user query -> Whoogle -> Google search -> Whoogle (filter) -> user
```

Google of course needs your search terms in order to pass results back through the Whoogle filter, but that filter step (both incoming and outgoing) strips out all other metadata and tags that Google appends to URLs and search results in order to gather more information from you. The filter also extends past Google results and filters out all result parameters that aren't strictly necessary to viewing the actual page. Your IP address is only exposed if you're running Whoogle locally and without an active VPN/proxy connection of some sort, but from what I understand at the moment, the majority of Whoogle instances are remote. 

Re: **Public Instance**
Probably not going to happen, and my reasoning for this is part philosophical stance and part lack of interest. I believe that the best balance of user privacy is achieved by eliminating as many middle-men as possible. Giving the power to an individual (me or whoever else) to run a public instance for everyone to use means a huge amount of blind trust, which in my opinion is already at its maximum with Google searches as-is. There's no easy way of verifying that the individual running the instance hasn't modified it before deployment and is secretly logging everything that you search for. So with this philosophy in mind, I intentionally tried to make Whoogle as easy to deploy as possible, from clicking a button to single command line runs, down to more detailed configuration. If someone feels like this is still too much work, then they should use something else. 

On top of that, running a public instance would be the easiest, lowest hanging fruit for Google to start throttling and/or blocking altogether. Having a single, central pipeline of information is much easier to shut down than thousands of small, personal instances. And it might be selfish, but I just don't feel like dealing with Google throttling/killing access for a particular instance and then getting bogged down with even more emails than I already get with people saying "X instance isn't working and it's your fault so fix it NOW". *Maybe* if I had more collaborators on the project to help out with stuff like this, but at the moment it's still more or less just me handling all bug requests, feature requests, help requests, feedback, complaints, etc. It's mostly manageable at the moment, but adding in maintenance of a public instance just sounds like it'd take away time from my gradual progress of addressing features/bugs that people actually want. 

All that being said, if someone else wanted to take on the task of maintaining a public instance, I'm happy to link to it in the README and direct people there if they're really just in the mood for a really quick demo.

**Comment by mendel5** [comment]
Thank you @benbusby for your detailed answer! 🚀
