### ISSUE TITLE
[FEATURE] Multiple Social Media Alternatives

### ISSUE THREAD

**Issue by 0xspade** [benbusby/whoogle-search#692]
Hi,

Is it possible to implement an array of multiple social media alternative sites? With that feature, we don't rely on one instance, and every time a user search, it randomly selects alternative social media.

**Comment by WitherCubes** [comment]
[farside.link](https://farside.link) is an option and it is used by whoogle.

**Comment by 0xspade** [comment]
> [farside.link](https://farside.link) is an option and it is used by whoogle.

I wonder, so if I don't specify the environment config: `WHOOGLE_ALT_WIKI`, `WHOOGLE_ALT_IMG`, etc… it will automatically randomize the selection of alternative SM links? As long as the environment config `WHOOGLE_CONFIG_ALTS` is set to `1`, am I correct?

**Comment by WitherCubes** [comment]
You need to set the environment variables like `WHOOGLE_ALT_WIKI=farside.link/wikiless`, `WHOOGLE_ALT_IMG=farside.link/imgin`, etc. (services that farside supports) and you should also set `WHOOGLE_CONFIG_ALTS` to `1`.

**Comment by benbusby** [comment]
By default, if you enable `WHOOGLE_CONFIG_ALTS` it will use Farside for all alternative frontends, no need to specify `farside.link/<service>` for each `WHOOGLE_ALT_<SERVICE>` var. Those variables should only actually be used if you only want to consistently visit one instance each time. 

Closing for now since I think that answers your question, but feel free to reopen if I'm mistaken!

**Comment by 0xspade** [comment]
Always need to add `/u`  whenever I search a profile on Instagram.
