### ISSUE TITLE
[QUESTION] Connection isn't secure only for my whoogle subdomain

### ISSUE THREAD

**Issue by ludoctl** [benbusby/whoogle-search#709]
Hi there,

My knowledge being full of gaps, I'm not sure where to look to solve that:
Got a bunch of services all hosted via docker behind the same nginx reverse proxy setup, all on subdomains over https with my Cloudflare issued Client certificate.

I get the "Connection isn't private/secure" and NET::ERR_CERT_INVALID (on chrome) and need to add an exception... though it isn't the case for any other of my services/subdomains. All subdomains are listed as hosts on the cloudflare certificates page... any idea where I should look?

**Comment by benbusby** [comment]
Hi @ludoctl. Without being able to see your nginx config, it's a little hard to diagnose what the issue could be. I have a similar setup to yours, with multiple services defined for different subdomains with each in their own nginx server block. Here's an example configuration:

```
server {
	server_name subdomain.domain.com;
	location / {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header Host $host;
		proxy_pass http://localhost:5000;

	}

	listen 443 ssl; # managed by Certbot
	ssl_certificate /etc/letsencrypt/live/subdomain.domain.com/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/subdomain.domain.com/privkey.pem; # managed by Certbot
	include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

Is your setup similar to that? Your cert definitions will likely point somewhere else since you're using Cloudflare certificates, but otherwise I'm assuming it's the same general configuration. I'm not familiar with using Cloudflare certificates, but can you verify that the certificate used for the site (found via the URL bar -> lock icon -> "Connection is Secure" -> "View certificate" or something like that) is what you'd expect in terms of common name and validity period?
