### ISSUE TITLE
Heroku Deploy Root url issue

### ISSUE THREAD

**Issue by Backup700** [benbusby/whoogle-search#77]
The root url of heroku deploy automatically downgrade to "http" after some time, even when user changes it to "https" manually.

When "http" root url is set then home page shows an warning i.e "parts of this page are not secure such as images"

When user set manually it to https that warning got removed.

-------

Also heroku deploy build seems lagged in recent changes like safe search & Search Suggestions.
Both are missing.

**Comment by benbusby** [comment]
The heroku app HTTPS problems are already documented, but I'm going to update the README with clearer instructions shortly. Ideally Heroku would set automatic HTTPS enforcement on their end, since they're the ones issuing the certificate, but for some reason they aren't. Once I update the README I'll merge `master` changes into the `heroku-app` branch and close this issue.

**Comment by benbusby** [comment]
Documented and heroku branch has been updated.
