### ISSUE TITLE
[BUG] Fly deployment Redux

### ISSUE THREAD

**Issue by vcg3rd** [benbusby/whoogle-search#772]
Something may have changed since [this issue](https://github.com/benbusby/whoogle-search/issues/468) but it appears a Whoogle deployment on Fly.io requires a paid tier.  I didn't understand a lot of what was discussed in issue 468, but I followed fly.io's guide.

First: "fly apps create --org personal --port 5000" is not correct, as issue 468 says, but it hasn't been changed in the README.   Following Fly's [guide](https://fly.io/docs/hands-on/create-app/) and, after all preceding steps issuing the command: `flyctl launch --image benbusby/whoogle-search:latest' one eventually is asked if he wants to deploy a postgresql database. 

Choosing yes and continuing results in being informed via email the deployment requires a pay tier.  Destroying the app with 'flyctl apps destroy' and repeating the process and choosing no results in being informed via email the deployment requires a pay tier.

I do not know how to verify a Whoogle deployment on Fly requires a paid tier, and if it does it is not a really a bug, and I apologize for calling it one.  However, I don't code; thus, the attempt at a simple deployment of a promising privacy search engine I control.

**Comment by benbusby** [comment]
Sorry for the delay -- I just got around to deploying Whoogle using Fly.io and can confirm that they require a paid account for deployment now.

I'm not sure why this was changed by them, but they've changed their platform a lot in the time since Whoogle had documented support for deploying with them. I've updated the instructions in the readme and included emphasis that this requires a paid account now.
