### ISSUE TITLE
[Enhancement] New Dark mode color scheme

### ISSUE THREAD

**Issue by Backup700** [benbusby/whoogle-search#78]
I found that current dark mode is too much dark, also text & other elements are not that clearly visible, so here are my color hex suggestions for new refreshed night blue theme.

Background color #222E3C
Search button, Whoogle title & Outline #59A8E2
Search page Links heading #64CEFD
Search page actual url text #7ABB58
Selected simple text background highlight #35475D
Selected Links selection background(Opaque) #61A9E144
Image search page button suggestion background #5FA8DC (keep text white)

I hope this implementation looks more polished in dark theme.

**Comment by benbusby** [comment]
Thanks for the suggestion! I'm going to start combining these into #60 so that it can all be tracked under one issue. Essentially nobody will be perfectly happy with any theme, so I'd prefer just adding the ability to have the user customize everything themselves rather than have me make a different theme every time someone wants a new one.

**Comment by Backup700** [comment]
Nice.
Please tweak dark theme save settings accordingly so that even when user switch theme from dark to light mode the last dark color scheme settings remained saved in memory. So that next time when user switch theme it won't need any tweaking in values.
