### ISSUE TITLE
[BUG] Inconsistent dark mode

### ISSUE THREAD

**Issue by gripped** [benbusby/whoogle-search#79]
**Describe the bug**
With dark mode set:
Front page. search-bar: black background, #685e79 text
Results page. search-bar:  white background, black text.

On both pages. search-bar-autocomplete-list: white background, black text.

I only just noticed this as I use a universal Stylus dark theme (on sites that can handle it), which worked perfectly on whoogle up to now, but failed to handle the auto-complete perfectly (transparency over the configuration button, not your problem!)  so I turned the style off briefly. To me the auto-complete results box is like staring at a light bulb :)

Also similar to  #78 the dark mode contrast is extreme. Dark greys for background and light greys for normal text are more pleasing (and less painful) to my eyes. But maybe a choice ? Normal, Dark and Extreme Dark ?
Wasn't sure whether to file as a bug or a feature request as it's a bit of both.

Still great work. 

**To Reproduce**
Enter a search term on front page.
Enter a search term on results page.

**Deployment Method**
- [ ] Other: [describe setup]
Manual install

**Version of Whoogle Search**
Github Master

**Desktop (please complete the following information):**
Linux (gentoo)
Firefox and Falkon 
 - Versions current

**Comment by benbusby** [comment]
I fixed the styling inconsistencies with the search field and the autocomplete suggestions -- thanks for reporting!

Regarding the requested theme changes, I'm going to start combining these into #60 so that it can all be tracked under one issue. Essentially nobody will be perfectly happy with any theme, so I'd prefer just adding the ability to have the user customize everything themselves rather than have me make a different theme every time someone wants a new one.

**Comment by gripped** [comment]
@benbusby 
That's much better. Thanks.
