### ISSUE TITLE
[BUG] Whoogle.click loading to startpage on mobile after adding as default search engine

### ISSUE THREAD

**Issue by JustAnEdiot** [benbusby/whoogle-search#861]
**Describe the bug**
- Whoogle.click loading to startpage on mobile after adding as default search engine 

**To Reproduce**
1. Add Whoogle to Firefox mobile (iOS), with the url https://whoogle.click/search?q=%s
2. Search for anything
3. Loads to the startpage

**Deployment Method**
- https://whoogle.click/ (the website)

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [x] Not sure

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [Firefox, Brave]
 - Version [Firefox - 106.0, Brave - 1.43]

**Smartphone (please complete the following information):**
 - Device: [iPad Pro 12.9" 5th generation (A2378)]
 - OS: [iOS 15.6.1]
 - Browser [Firefox, Brave]
 - Version [Firefox - 106.0, Brave - 1.43]

**Additional context**
I'm able to add Whoogle as a search engine on every desktop device I have been able to try

**Comment by jacr13** [comment]
Hello, 

I have tested your instance on my phone, and it works perfectly you have just to set https://www.whoogle.click/search?q=%s
instead of https://whoogle.click/search?q=%s (note the added www). 
It seems that https://whoogle.click is redirecting to https://www.whoogle.click/ without the params.

For startpage it's because you didn't change your default engine to whoogle, or that your https://whoogle.click redirection was set to startpage.

**Comment by JustAnEdiot** [comment]
oh thanks!

that worked perfectly!
