### ISSUE TITLE
[QUESTION] <No image thumbnails after upgrading to 0.8 version>

### ISSUE THREAD

**Issue by brackhap** [benbusby/whoogle-search#891]
After upgrading my private instance to 0.8 version, No images are shown in images search results ([see this screenshot](https://imgur.com/a/GdGjUgB)). I am using portainer to deploy whoogle on my vps.

Any ideas?

**Comment by benbusby** [comment]
Could you repeat the request with the network tab in the browser console open, and see if the image requests are failing? If they are, what's the status code returned by each request?

My guess is that there's an issue with decrypting the image path. It might help to clear all cookies associated with your instance, since decryption was previously tied to a session ID stored in the cookie.

**Comment by brackhap** [comment]
After checking the network tab, all images returned a 302 status code, and the request url is weired:

`https://mydomain.xyz/https, https://mydomain.xyz/element?url=gAAAAABjhS86fmEPgJbgxZJQUC-nH0x7SCy4nYriFtjKcwfmzQL2ysAPPHsPZn7r3PYPrvfLYVbu67YRY3biIANEr9xfEirVSbcFshemZZXSz7RE7GowyyyYmds8FyzDQ6bzJ3HCf2T9h9xeXFTxMKUZwd4g5iODJn5pSyksmhPzFFbdbo8Vtj2wApbzCBltaiN0rYUUHG96DkHHCFJh8u0pTd2EMvb2gkqUl5pihk5kDQYgUZVMbCM=&type=image/png`

I've cleared all the cookies and used different new browsers but the issue persists.

**Comment by benbusby** [comment]
I believe this should be fixed as of 0310f0f5421cb3984f947bb549866c1e0457ae5b (available on the `latest` tag if you're using Docker) but let me know if it persists.
