### ISSUE TITLE
[QUESTION] How to check if socks proxy is working?

### ISSUE THREAD

**Issue by ForceConstant** [benbusby/whoogle-search#893]
I setup the the proxy, but how to verify that it is actually working? 

Thanks.

**Comment by benbusby** [comment]
If any searches succeed while the proxy is configured, then it's working. If there were a configuration issue, then searches would fail since all requests are routed through the proxy when those environment variables are set. 

Alternatively, if the proxy is located in a different region than where the instance is hosted, you could do a simple location based search (i.e. "restaurants near me") and see if results are returned for the proxy's region and not the instance's. 

Feel free to reopen if you need more help.
