### ISSUE TITLE
[Waterfox] Unable set primary search engine

### ISSUE THREAD

**Issue by valaria247** [benbusby/whoogle-search#92]

**Comment by benbusby** [comment]
I'll need more info on this. Does it give an error message? Can you access `<instance url>/opensearch.xml`? Does it say the search engine has been set but doesn't actually add it to the list under Waterfox preferences? 

I have it set up on Firefox without any issues, but there could be an opensearch compatibility issue with Waterfox since they rely on older versions of Firefox (from what I recall at least, I could be way off).

**Comment by valaria247** [comment]
I thought you use it and no, they have both versions as i think. Waterfox only allows to add custom search engines through "Find more search engines" then it redirect to addons page.

Waterfox Current

**Comment by valaria247** [comment]
So i have to open an issue in his repository but never get fixed easily then any other technical way to solve that?

**Comment by benbusby** [comment]
Ah I see. Unfortunately I'm not sure of a different way to fix that. I'll close this issue for now since it's not really a Whoogle issue, but I'll revisit this if I have some time to look into how Waterfox is implementing search engines and see if there's a way of just manually inserting the opensearch file.
