### ISSUE TITLE
[BUG] Settings not used when searching from URL bar

### ISSUE THREAD

**Issue by TheSunCat** [benbusby/whoogle-search#929]
**Describe the bug**
Hi! I'm hosting a Whoogle instance in France, but would like the interface to be presented in English on my device. In the homepage's options, I set the fields as follows:
![image](https://user-images.githubusercontent.com/44881120/211623732-500106d7-557d-4201-ab03-39de40c509e4.png)
If I make a search from that page, this is correctly set and the results are in English. However, if I search from the URL bar, the results are in French.

**To Reproduce**
1. Add Whoogle as a search engine
2. Change the language setting
3. Perform a search
4. Observe option not being applied

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 108.0.2 (64-bit)

**Comment by HotarunIchijou** [comment]
Can approve this. This is because the "?" isn't added before "preferences=..." in the url address and the settings are ignored. In browsers, where you can change the custom search engine url (e.g. Firefox, Firefox mobile, Chrome desktop). But in the browsers, where you can't (e.g. vanilla Chromium and Chromium mobile forks, like Bromite) it's a really big problem

**Comment by TheSunCat** [comment]
Have you found a workaround for Firefox? I don't see where to customize the search url in the settings.

**Comment by HotarunIchijou** [comment]
@TheSunCat I was frong. In firefox desktop you can't change search engine url (maybe it's possible in some other places, like in about:config, but not in settings). Maybe [this](https://support.mozilla.org/en-US/questions/1365694) will be helpful for you

**Comment by TheSunCat** [comment]
Thanks! I was able to add it by exporting the JSON file of the saved search engines and editing the URL there. This could definitely be handled better...
Can Whoogle not save the settings as a cookie and read it back when a search is performed?

**Comment by HotarunIchijou** [comment]
@TheSunCat I think it can, because all preferences is in the URL.

**Comment by TheSunCat** [comment]
I mean, instead of saving the preferences in the URL, could it instead save them as a cookie? This would have the added benefit of making Whoogle links shorter and thus easier to share.

**Comment by HotarunIchijou** [comment]
@TheSunCat I think, you can

**Comment by benbusby** [comment]
Apologies for the delay! This should be fixed now. The issue had to do with how browsers access the opensearch template. Since the browser makes the request for the opensearch template outside of the context of the user's session, the `preferences` field is auto-populated with the instance's default state. That argument has been removed from the template (since it isn't strictly necessary there anyways), so this shouldn't be a problem anymore.

**Comment by TheSunCat** [comment]
Thank you!
