### ISSUE TITLE
[Development] All in one translation site

### ISSUE THREAD

**Issue by temporallyaccount** [benbusby/whoogle-search#93]
Do you mind to introduce Whootra? or OneTranslate? 🥰 
I mean all in one page as replacement for most popular translation services. google translate, yandex translate, bing translate and allow some easy ways for users to add custom translation services as well.

I have noticed some cloud translation platforms similar crowdin has such integration inside webapp for provide additional help for translators. This's not a priority request but if you may have some free time.

**Comment by benbusby** [comment]
I've looked into this a little, and I think it's a bit out of scope for what the project should be focused on. Google/Yandex/Bing/etc translation are all centralized services with a lot of people working to support them. With Whoogle being primarily deployed per-user, it wouldn't make a lot of sense to build in a third party translation API since it'd likely be something I'd have to pay for. So for now, I'm gonna close this issue, but I'll keep it in mind if I come across something that might work.
