### ISSUE TITLE
Some issues I have found with Greek language

### ISSUE THREAD

**Issue by comfuzio** [benbusby/whoogle-search#931]
Hello :)
I am running whoogle as a Container in Proxmox dedicated server in Hetzner's datacenter in Finland.
Installation was via the script provided here "https://tteck.github.io/Proxmox/" in the "Miscellaneous" category.
As container it is behind NPM in my server (and most likely will go behind CloudFlare as well).
Url: https://whoogle.gr

Issue no1:
When I do a search all results comeback in German OR from German websites first. No problem with the country or the language don't get me wrong, but i'd assume it would detect my country and show relative results from my country first or at least in International language English and not in German.

Issue no2:
If i set via the configuration that the language is Greek, it still says "Search" instead of "Αναζήτηση"
![image](https://user-images.githubusercontent.com/30821243/213363815-f48f90b2-e7f8-4dc2-a915-902b828c6494.png)

And as a connection with Issue no1, also that I change the country into Greece still the results I am getting are in German.

I can probably help with changing the "Search" into "Αναζήτηση" if I can locate the language file (not a programmer here) but for issue no1, I have no idea how to help other than just reporting it.

Kind regards,
George

**Comment by ahmad-alkadri** [comment]
Hi George @comfuzio ! I'm not familiar with Proxmox and the script, but I just tried your Whoogle instance and things are returned in Greek, so I guess you've modified the config a bit and put Greek as the default language? So Issue no. 1 seems to be resolved then?

![screenshot-whoogle gr-2023 01 24-23_55_16](https://user-images.githubusercontent.com/22837764/214439435-9442ed50-b15b-47ed-a824-f61790546251.png)

About the second Issue, I believe it's because there is no Greek language yet in the  [translations.json](https://github.com/benbusby/whoogle-search/blob/main/app/static/settings/translations.json)` located in the app/static/settings. As a matter of fact it's not the only one; there are other languages that haven't gotten their own translations yet. 

If you want to add the translations, you can make fork this repo, make a branch and then edit that translations.json file with the Greek translations, then make a PR to merge it into main. 

Let me know if I can help; I'm also in the middle of working for a translation for my own native language.

**Comment by comfuzio** [comment]
Thank you for your kind response! I have deleted that container and rebuild it via portainer where i was able to configure it. I have solved the issue just not for the original post.

I have already forked it, now that i know where to look thanks to you, i will edit it and ask for a merge .

Thank you

**Comment by comfuzio** [comment]
I Think I have done it, it is not 100% translation since some terms do not exist in Greek (example Regex).
Some I will edit later after work :)
Thank you again

**Comment by ahmad-alkadri** [comment]
> I Think I have done it, it is not 100% translation since some terms do not exist in Greek (example Regex).
> 
> Some I will edit later after work :)
> 
> Thank you again

That's great! Good luck then!
