### ISSUE TITLE
[QUESTION] How to run whoogle with uwsgi ?

### ISSUE THREAD

**Issue by damionx7** [benbusby/whoogle-search#99]
I want to run whoogle with uwsgi. What would be the sample uwsgi file for this.

**Comment by benbusby** [comment]
Since Whoogle is a pretty standard Flask app, most guides for uwsgi + flask will work fine. [This article](https://hackersandslackers.com/deploy-flask-uwsgi-nginx/) seems to be a good enough walk through for a similar setup -- it uses the default/standard flask setup (port 5000, `app` module) so you shouldn't have to modify much.

**Comment by arankaren** [comment]
Some example?. I need help. what should I put in wsgi.py?

```
[uwsgi]
# require uwsgi-plugin-python
master=true
plugin=python
uid=cerebelum
gid=http
# the base directory (full path)
chdir = /srv/http/whoogle-search
# Module
module = wsgi:app
# the virtualenv (full path)
pythonpath = /srv/http/whoogle-search
virtualenv = /srv/http/whoogle-search/venv
enable-threads = true
processes = 1
threads = 1
# daemonize = /var/log/uwsgi/whoogle-search.log
pidfile = /run/uwsgi/whoogle-search.pid
socket = /run/uwsgi/whoogle-search.sock
# http = 127.0.0.1:8888
chmod-socket=664
socket-timeout = 600
vacuum = true
die-on-term = true
```
